name: driversapp
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  smooth_page_indicator: ^1.0.0+2
  flutter_svg: ^1.0.0
  material_color_gen: ^2.0.0
  firebase_core: ^1.10.6
  firebase_analytics: ^9.0.4
  firebase_auth: ^3.3.4
  cloud_firestore: ^3.1.5
  firebase_app_check: ^0.0.6+3
  flutter_verification_code: ^1.1.1
  animate_do: ^2.0.0
  hive: ^2.2.3
  build_runner: ^2.2.0
  map_launcher: ^2.3.0
  hive_generator: ^1.1.3
  hive_flutter: ^1.1.0
  dropdown_search: ^5.0.2
  flutter_ringtone_player: ^3.2.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/